// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiwuVwgAxOTHNl_LezApZlDrEU5LxyHzw',
    appId: '1:87500511998:android:12a1b3ab70afae629323af',
    messagingSenderId: '87500511998',
    projectId: 'tasks-fc0cf',
    storageBucket: 'tasks-fc0cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv2qpPCeDiO5HgaFCo8-nY9LeGvL-sG2c',
    appId: '1:87500511998:ios:db3969eb9bf6a5009323af',
    messagingSenderId: '87500511998',
    projectId: 'tasks-fc0cf',
    storageBucket: 'tasks-fc0cf.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsevT2KyX69l5143rCK6aWktYaZWi1wZs',
    appId: '1:87500511998:web:17d8b2b735ba075c9323af',
    messagingSenderId: '87500511998',
    projectId: 'tasks-fc0cf',
    authDomain: 'tasks-fc0cf.firebaseapp.com',
    storageBucket: 'tasks-fc0cf.firebasestorage.app',
  );

}